const vehicles = [
    {
        id: "1",
        originDistrict: "Sylhet",
        destinationDistrict: [],
        type: "Van",
        typeDetails: "Daihatsu Hijet",
        driverName: "Abdul Goni",
        driverPhone: "12345678901",
        address: "Rangpani, Sylhet",
        intraCost: 150,
        interDistrict: false,
        percentage: 0.2,
        interCost: 0,
        maxPassengers: 8,
        imageUrl: "https://japanesenostalgiccar.com/wordpress/wp-content/uploads/2021/10/DaihatsuHiJetS65-AtraiLTypeHighRoof-1981-04.jpg"
    },
    {
        id: "2",
        originDistrict: "Dhaka",
        destinationDistrict: ["Sylhet", "Mymensingh", "Chittagong", "Khulna", "Rajshahi", "Barishal"],
        type: "Microbus",
        typeDetails: "Toyota Hilux",
        driverName: "Raju Miah",
        driverPhone: "01768890525",
        address: "Arambag, Dhaka",
        intraCost: 200,
        interDistrict: true,
        percentage: 0.2,
        interCost: 2500,
        maxPassengers: 10,
        imageUrl: "https://www.aboudcar.com/wp-content/uploads/2023/11/Photo-192-1-1024x576.jpg"
    },
    {
        id: "3",
        originDistrict: "Chittagong",
        destinationDistrict: ["Sylhet", "Mymensingh", "Dhaka", "Khulna", "Rajshahi", "Rangpur"],
        type: "Microbus",
        typeDetails: "Toyota Hiace",
        driverName: "Nikhil Chandra",
        driverPhone: "01712346433",
        address: "Karnaphuli, Chittagong",
        intraCost: 200,
        interDistrict: true,
        percentage: 0.2,
        interCost: 3000,
        maxPassengers: 12,
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/62/Toyota_Hiace_H200_511.JPG"
    },
    {
        id: "4",
        originDistrict: "Rajshahi",
        destinationDistrict: [],
        type: "Sedan",
        typeDetails: "Nissan Sunny",
        driverName: "Jamil Hossain",
        driverPhone: "01859175332",
        address: "Boalia, Rajshahi",
        intraCost: 250,
        interDistrict: false,
        percentage: 0.2,
        interCost: 0,
        maxPassengers: 5,
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/11/1995_Nissan_Sunny_%28B14%29_EX_Saloon_%28front%29.jpg"
    },
    {
        id: "5",
        originDistrict: "Khulna",
        destinationDistrict: ["Dhaka", "Rajshahi", "Rangpur", "Barishal"],
        type: "Sedan",
        typeDetails: "Toyota Corolla",
        driverName: "Sadek Islam Tutul",
        driverPhone: "01521654212",
        address: "Khalishpur, Khulna",
        intraCost: 230,
        interDistrict: true,
        percentage: 0.2,
        interCost: 300,
        maxPassengers: 6,
        imageUrl: "https://en.wikipedia.org/wiki/File:Corollavan.jpg"
    },
    {
        id: "6",
        originDistrict: "Rangpur",
        destinationDistrict: [],
        type: "Van",
        typeDetails: "Mahindra Supro",
        driverName: "Hanif Ali",
        driverPhone: "01512356889",
        address: "Pirganj, Rangpur",
        intraCost: 200,
        interDistrict: false,
        percentage: 0.2,
        interCost: 0,
        maxPassengers: 10,
        imageUrl: ""
    },
    {
        id: "7",
        originDistrict: "Sylhet",
        destinationDistrict: ["Dhaka", "Chittagong", "Rajshahi", "Khulna", "Rangpur", "Barishal"],
        type: "Microbus",
        typeDetails: "Mitsubishi Delica",
        driverName: "Rahim Uddin",
        driverPhone: "01314562245",
        address: "Kadamtali, Sylhet",
        intraCost: 200,
        interDistrict: true,
        percentage: 0.2,
        interCost: 350,
        maxPassengers: 12,
        imageUrl: ""
    },
    {
        id: "8",
        originDistrict: "Barishal",
        destinationDistrict: ["Dhaka", "Chittagong", "Rajshahi", "Khulna", "Rangpur", "Sylhet"],
        type: "Microbus",
        typeDetails: "Toyota Hiace",
        driverName: "Zamil Rehman",
        driverPhone: "01323225698",
        address: "Bakerganj, Barishal",
        intraCost: 200,
        interDistrict: true,
        percentage: 0.2,
        interCost: 350,
        maxPassengers: 12,
        imageUrl: ""
    },
    {
        id: "9",
        originDistrict: "Mymensingh",
        destinationDistrict: ["Dhaka", "Chittagong", "Rajshahi", "Khulna", "Rangpur", "Sylhet"],
        type: "Sedan",
        typeDetails: "Toyota Premio",
        driverName: "Asgar Ali",
        driverPhone: "01323225698",
        address: "Mymensingh Sadar, Mymensingh",
        intraCost: 250,
        interDistrict: true,
        percentage: 0.2,
        interCost: 400,
        maxPassengers: 6,
        imageUrl: ""
    }
];

module.exports = vehicles;